# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30c131962b75844fd5d9eb0c2f96bae6bf3425e8c6816c7be1ca06a90b217f0475f38021d74faab0897cbba5ce016970543db7f686501084bc7a4b44e5f951b7

test:
  secret_key_base: ce31ee12fd6bc251d2b34623600c9dfbe79352bad46843c9a4cbb724d6a2d709a6f5af33b6139c93b289ee039484e9b64e3141b0f2654bd9c097f8ae5785ee6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
